# Ruta al código fuente
sonar.sources=src/
sonar.exclusions=**/__init__.py

# Ruta a los tests
sonar.tests=tests/

# Aquí se puede especificar la ruta al reporte de cobertura generado por pytest-cov
sonar.python.coverage.reportPaths=coverage.xml